# -*- coding: utf-8 -*-
"""Tesis_data_poo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rFCKlcpNfeIZW7mLm4z814pRGDDsDb51
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
#from statsmodels.tsa.stattools import adfuller
#import statsmodels.api as sm
#from statsmodels.tsa.stattools import coint #ENGLE-GRANGER

class TimeSeries:

    """
    Es una clase pensada para hacer gráficas de las series de tiempo, así como acceder rápidamente
    a sus rendimientos normales, logarítmicos e incluso reescalarlos con MimMaxScaler.
    ATRIBUTOS:
    .name: String con el nombre de la serie
    .color: String con el color que la serie tendrá al graficarla
    .data: Pandas Series con los datos.
    """

    def __init__(self, data:pd.Series, name:str, color:str):
        self.name = name
        self.color = color
        self.data  = data
        self.data.name = name

    # ---------------------------------------
    # Métodos de limpieza / preprocesamiento
    # ---------------------------------------

    def str_to_date(self) -> None:
        """Convierte los índices de .data a tipo datetime (modifica in place)."""
        self.data.index = pd.to_datetime(self.data.index)

    def quitar_findes(self) -> pd.Series:
        """Quita sábados y domingos de .data (modifica in place)."""
        self.str_to_date()
        self.data = self.data[self.data.index.weekday < 5]
        return self.data

    def cut(self, start_date: str, end_date: str) -> pd.Series:
        """Recorta .data  entre dos fechas (inclusive)."""
        self.data = self.data.loc[start_date:end_date]
        return self.data

    # --------------------------
    # Métodos de transformación
    # --------------------------


    def minmax(self, feature_range = (0, 1)) -> pd.Series:
      """
      Reescala .data entre el rango especificado (por defecto (0, 1)).
      Devuelve una pandas.Series con los datos reescalados.
      """

      scaler = MinMaxScaler(feature_range= feature_range)
      scaled = scaler.fit_transform(self.data.values.astype(np.float32).reshape(-1, 1))
      serie = pd.Series(scaled.flatten(), index = self.data.index, name = self.name)
      return TimeSeries(serie, self.name, self.color)

    def nreturns(self, scaled:bool = False, feature_range = (0, 1)) -> pd.Series:
      """
      Calcula los rendimientos normales de .data, si scaled = True reescala los rendimientos
      entre el rango especificado (por defecto (0, 1)).
      Devuelve una pandas.Series con los rendimientos.
      """
      S = self.data.values.astype(np.float32)
      rendimientos = np.zeros(len(S))
      for i in range(1, len(S)):
        rendimientos[i] = (S[i] - S[i-1])/S[i-1]

      Serie = pd.Series(rendimientos[1:], index = self.data.index[1:], name = self.name)
      if scaled:
        scaler = MinMaxScaler(feature_range= feature_range)
        scaled = scaler.fit_transform(Serie.values.reshape(-1, 1))
        Serie = pd.Series(scaled.flatten(), index = Serie.index, name = self.name)
      return TimeSeries(Serie, self.name, self.color)


    def logreturns(self, scaled:bool = False, feature_range = (0, 1)) -> pd.Series:
      """
      Calcula los rendimientos logarítmicos de .data, si scaled = True reescala los rendimientos
      entre el rango especificado (por defecto (0, 1)).
      Devuelve una pandas.Series con los rendimientos.
      """

      S = self.data.values.astype(np.float32)
      rendimientos = np.zeros(len(S))
      for i in range(1, len(S)):
        rendimientos[i] = np.log(S[i]/S[i-1])
      Serie = pd.Series(rendimientos[1:], index = self.data.index[1:], name = self.name)
      if scaled:
        scaler = MinMaxScaler(feature_range= feature_range)
        scaled = scaler.fit_transform(Serie.values.reshape(-1, 1))
        Serie = pd.Series(scaled.flatten(), index = Serie.index, name = self.name)

      return TimeSeries(Serie, self.name, self.color)

def same_dates(Series: list[TimeSeries], referencia: pd.Series) -> list:
  """
  Toma una lista  (Series) de TimeSeries, y una pandas.Series de referencia.
  Busca índices en todos los elementos de Series que no estén en referencia,
  remueve de cada elemento de Series los valores con todos esos índices.
  Retorna la lista modificada (todos los elementos tienen los mismos índices).

  """
  FALTANTES = []
  for I in Series:
    #En la lista vacía guardamos los días que están las criptos pero no en los indices
    FALTANTES.append(referencia.index.difference(I.data.index))
    #Hacemos una lista con todos los días que no están en por lo menos uno de los indices
  UFALTANTES = list(set(date for dif in FALTANTES for date in dif))

  for i in range(len(Series)):
    for date in UFALTANTES:
      Series[i].data = Series[i].data.drop(date, errors='ignore')
  return Series

def make_df(series_list: list[TimeSeries], trans: str = None, **kwargs) -> pd.DataFrame:
    """
    Organiza una lista de objetos TimeSeries en un DataFrame,
    aplicando el método `trans` si se especifica.

    Parámetros:
    - series_list: lista de objetos TimeSeries
    - trans: nombre del método (string) como 'nreturns', 'logreturns', etc.
    - kwargs: argumentos adicionales para el método

    Retorna:
    - DataFrame con cada serie como una fila
    """
    precios = {}

    for ts in series_list:
        if trans:
            metodo = getattr(ts, trans)
            serie = metodo(**kwargs)
        else:
            serie = ts.data

        precios[serie.name] = serie

    return pd.DataFrame(precios).T

def color_complementario(hex_code):
    """
    Toma el código hexadecimal de un color
    y devuelve el código hexadecimal del color complementario.
    """

    hex_code = hex_code.lstrip('#')

    # Convierte el código hex a componentes RGB
    r = int(hex_code[0:2], 16)
    g = int(hex_code[2:4], 16)
    b = int(hex_code[4:6], 16)

    # Calcula el complementario
    comp_r = 255 - r
    comp_g = 255 - g
    comp_b = 255 - b

    # Convierte de nuevo a formato hexadecimal
    return "#{:02X}{:02X}{:02X}".format(comp_r, comp_g, comp_b)

start_date = '2017-11-09'
end_date = '2025-02-07'
rutas = ["Nikkei-2014-2025.csv", "SP500-2014-2025.csv", "DAX40-2014-2025.csv", "FTSE250-2014-2025.csv",
         "MEX-2014-2025.csv", "BTC-2014-2025.csv", "ETH-2014-2025.csv", "XRP-2014-2025.csv",
         "Doge-2014-2025.csv", "Tether-2014-2025.csv"]
nombres = ["NIKKEI", "SP500", "DAX40", "FTSE250", "MEX", "BTC", "ETHEREUM", "XRP", "DOGE", "TETHER"]
colores = ['cyan', 'blue', 'teal', 'purple', 'royalblue', 'red', 'orangered', 'gold',  'crimson', 'darkorange']
precios_time_series = []

for i in range(len(rutas)):
  data = pd.read_csv(rutas[i]).iloc[0, 1:]
  ts = TimeSeries(data, nombres[i], colores[i])
  ts.data = ts.quitar_findes()
  ts.data = ts.cut(start_date, end_date)
  precios_time_series.append(ts)
precios_time_series = same_dates(precios_time_series, precios_time_series[5].data)
listed_nreturns = [TimeSeries(ts.nreturns(), ts.name, ts.color) for ts in precios_time_series]
listed_logreturns = [TimeSeries(ts.logreturns(), ts.name, ts.color) for ts in precios_time_series]
ref_time_series = precios_time_series[0]

#plt.figure(figsize = (25, 6))
#for ts in precios_time_series:
#  ts.data.plot(color = ts.color, label = ts.name)
#  plt.xticks(ts.data.index[::30], rotation = 45)
#  plt.grid()
#  plt.legend()

dict_colores = {
    'cyan': '#00FFFF',
    'blue': '#0000FF',
    'teal': '#008080',
    'purple': '#800080',
    'royalblue': '#4169E1',
    'red': '#FF0000',
    'orangered': '#FF4500',
    'gold': '#FFD700',
    'crimson': '#DC143C',
    'darkorange': '#FF8C00'
}

colores_complementarios = [color_complementario(dict_colores[color]) for color in colores]

#plt.figure(figsize = (25, 6))
#for ts, i in zip(precios_time_series, range(10)):
#  ts.minmax().plot(color = ts.color, label = ts.name)
#  ts.minmax().map(lambda x:-x).plot(color =colores_complementarios[i], label = "-"+ts.name)
#  plt.grid()
#  plt.xticks(ts.data.index[::30], rotation = 45)
#  #plt.legend()
#  plt.show(False)