# -*- coding: utf-8 -*-
"""mis_tfunciones_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gi40URnKUw8AtMVeNcocLL4qNxhcrGT-
"""


import pandas as pd
import numpy as np
import dcor
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt


def str_to_date(s: pd.Series) -> pd.Series:
  """
Toma una serie con índices de tipo string y la convierte a tipo datetime
  """
  s.index = pd.to_datetime(s.index)
  return s


def quitar_findes(s: pd.Series) -> pd.Series:
  """
  Toma una serie de tiempo "s", convierte los índices a fechas
  y quita los fines de semana. Devuelve la serie sin fines de semana
  """
  #Convertimos los índices a fechas
  s = str_to_date(s)
  #Quitamos los fines de semana
  s = s[s.index.weekday < 5]
  return s


def cut(s: pd.Series, start_date:str, end_date:str) -> pd.Series:
  """
  Toma una serie de tiempo "s" y dos cadenas de texto "start_date"
  y "end_date" en formato 'AAAA-MM-DD', devuelve la serie
  recortada para que inicie y termine en las fecha indicadas.
  """
  s = s.loc[start_date:end_date]
  return s


def nreturns(s: pd.Series) -> pd.Series:
  """
  Toma una serie de tiempo y devuelve una serie con los
  rendimientos normales
  """
  S = s.values.astype(np.float32)
  rendimientos = np.zeros(len(S))
  for i in range(1, len(S)):
    rendimientos[i] = (S[i] - S[i-1])/S[i-1]
  nombre_base = s.name if s.name is not None else "sin_nombre"
  return pd.Series(rendimientos[1:], index = s.index[1:], name = nombre_base + "_nr")


def logreturns(S: pd.Series) -> pd.Series:
  """
Toma una serie de tiempo "S" y devuelve una serie con los rendimientos
logarítmicos
  """
  valores = S.values.astype(np.float32)
  logret = np.zeros(len(valores))
  for i in range(1, len(valores)):
      logret[i] = np.log(valores[i]/valores[i-1])
  nombre_base = S.name if S.name is not None else "sin_nombre"
  return pd.Series(logret[1:], index = S.index[1:], name = nombre_base + "_lr")


def minmax(s: pd.Series, feature_range = (0, 1)) -> pd.Series:
  """
  Toma una serie de tiempo y devuelve una serie con los
  rendimientos normalizados usando el método MinMaxScaler
  """
  scaler = MinMaxScaler(feature_range= feature_range)
  scaled = scaler.fit_transform(s.values.reshape(-1, 1))
  nombre_base = s.name if s.name is not None else "sin_nombre"
  return pd.Series(scaled.flatten(), index = s.index, name = nombre_base + "_mm")


def DCC_matrix(M: np.array) -> np.array:
  """
Toma una matriz con N renglones, devuelve una matriz
NxN con los DCC entre cada una de las  N series
  """
  N = M.shape[0]
  DCC_m = np.zeros((N,N))
  for i in range(0, N, 1):
    for j in range(0, N, 1):
      DCC_m[i,j] = dcor.distance_correlation(M[i][0:], M[j][0:])

  return DCC_m


def same_dates(Series: list, referencia: pd.Series) -> list:
  FALTANTES = []
  for I in Series:
    #En la lista vacía guardamos los días que están las criptos pero no en los indices
    FALTANTES.append(referencia.index.difference(I.index))
    #Hacemos una lista con todos los días que no están en por lo menos uno de los indices
  UFALTANTES = list(set(date for dif in FALTANTES for date in dif))

  for i in range(len(Series)):
    for date in UFALTANTES:
      Series[i] = Series[i].drop(date, errors='ignore')
  return Series


def Bollinger_bands(serie: pd.Series, window = 20, n=2):
    """
    Calcula las bandas de Bollinger para una serie de tiempo.
    """
    media_movil = serie.rolling(window=window).mean()
    desv_estand = serie.rolling(window=window).std()
    upper_band = media_movil + n * desv_estand
    lower_band = media_movil - n * desv_estand
    return media_movil, upper_band, lower_band


def my_plotted_bb(serie:pd.Series, title:str, bands = None,   ROI: list = None, *args, **kwargs):
    
    """
    Grafica las bandas de Bollinger de una serie de tiempo.
    ROI = [start_date, end_date], 'yyyy-mm-dd'
    bands = [Moving_averge, upper_band, lower_band]
    if bands is None, reutrns a moving average en the Bollinger bands for serie
    """
    color_s = "#ED553B"
    color_ma = "#F6D55C"
    color_bu = "#3CAEA3"
    color_bl ="#20639B"

    if bands is None:
       bb= Bollinger_bands(serie, **kwargs)
       ma = bb[0]
       bu = bb[1]
       bl = bb[2]
      
    else:
      ma = bands[0]
      bu = bands[1]
      bl = bands[2]
       
    if ROI is None:

       plt.figure(figsize=(30,10))
       plt.title(title, fontsize=20)
       BU, = plt.plot(bu, color = color_bu)
       BL, = plt.plot(bl,  color = color_bl)
       CA, = plt.plot(serie, color = color_s)
       MA, =plt.plot(ma, color=color_ma)

       plt.fill_between(bu.index, bu, bl, alpha=0.15)
       plt.xticks(serie.index[::60], rotation=45)
       handles, labels = plt.gca().get_legend_handles_labels()

       #Reordenar los handles y labels (cambiamos el orden en que se muestran en la leyenda)
       plt.legend(handles=[CA, BU, MA, BL], labels=["Precios", "BU", "MA", "BL"], fontsize=20)
       plt.grid()
       plt.show()

    else:
       start_date = ROI[0]
       end_date = ROI[1]
       plt.figure(figsize=(30,10))
       plt.title(title, fontsize=20)
       BU, = plt.plot(bu[start_date:end_date], color = color_bu)
       BL, = plt.plot(bl[start_date:end_date], color = color_bl)
       CA, = plt.plot(serie[start_date:end_date], color = color_s)
       MA, =plt.plot(ma[start_date:end_date], color=color_ma)
      
       plt.fill_between(bu[start_date:end_date].index, bu[start_date:end_date], bl[start_date:end_date], alpha=0.15)
       plt.xticks(serie.loc[start_date:end_date].index[::31], rotation=45)
       handles, labels = plt.gca().get_legend_handles_labels()

       #Reordenar los handles y labels (cambiamos el orden en que se muestran en la leyenda)
       plt.legend(handles=[CA, BU, MA, BL], labels=["Precios", "BU", "MA", "BL"], fontsize=20)
       plt.grid()
       plt.show()
    return ma, bu, bl


def split_epochs(M: np.array, dt: int) -> np.array:
  """
  Toma una matriz NxT y la divide en submatrices Nxdt
  Devuelve int(t/dt) submatrices Nxdt y la matriz residual
  (si la hay)
  """
  N, t = M.shape
  n = int(t/dt)
  residuo = t - int(n*dt)
  Epocas = np.zeros((n, N, dt))
  for i in range(n):
    Epocas[i] = M[:, i*dt:(i+1)*dt]
  
  E_res = M[:, -residuo:]
  return Epocas, E_res

#TRATAMIENTO DE DATOS

sp500 = pd.read_csv("SP500-2014-2025.csv").iloc[0 ,1:]
nikkei = pd.read_csv("Nikkei-2014-2025.csv").iloc[0 ,1:]
ftse = pd.read_csv("FTSE250-2014-2025.csv").iloc[0 ,1:]
dax = pd.read_csv("DAX40-2014-2025.csv").iloc[0 ,1:]
mex = pd.read_csv("MEX-2014-2025.csv").iloc[0 ,1:]
btc = pd.read_csv("BTC-2014-2025.csv").iloc[0 ,1:]
eth = pd.read_csv("ETH-2014-2025.csv").iloc[0 ,1:]
xrp = pd.read_csv("XRP-2014-2025.csv").iloc[0 ,1:]
tether = pd.read_csv("Tether-2014-2025.csv").iloc[0 ,1:]
doge = pd.read_csv("Doge-2014-2025.csv").iloc[0 ,1:]

nombres = ["SP500", "Nikkei", "FTSE250", "DAX40", "MEX", "BTC", "TETHER", "XRP", "ETHEREUM", "DOGE"]
Series = [sp500, nikkei, ftse, dax, mex, btc, tether, xrp, eth, doge]
for s, n in zip(Series, nombres):
   s.name = n


start_date = '2017-11-09'
end_date = '2025-02-07'

for i in range(0, 5, 1):
    Series[i] = cut(str_to_date(Series[i]), start_date, end_date)
for i in range(5, 10, 1):
    Series[i] = cut(quitar_findes(Series[i]), start_date, end_date)

Series = same_dates(Series, referencia = btc)


#Datos procesados
sp500 = Series[0]
nikkei = Series[1]
ftse = Series[2]
dax = Series[3]
mex = Series[4]
btc = Series[5]
tether = Series[6]
xrp = Series[7]
eth = Series[8]
doge = Series[9]


#Rendimientos normales
sp500_nr = nreturns(Series[0])
nikkei_nr = nreturns(Series[1])
ftse_nr = nreturns(Series[2])
dax_nr = nreturns(Series[3])
mex_nr = nreturns(Series[4])
btc_nr = nreturns(Series[5])
tether_nr = nreturns(Series[6])
xrp_nr = nreturns(Series[7])
eth_nr = nreturns(Series[8])
doge_nr = nreturns(Series[9])


#Rendimientos logarítmicos 
sp500_lr = logreturns(Series[0])
nikkei_lr = logreturns(Series[1])
ftse_lr = logreturns(Series[2])
dax_lr = logreturns(Series[3])
mex_lr = logreturns(Series[4])
btc_lr = logreturns(Series[5])
tether_lr = logreturns(Series[6])
xrp_lr = logreturns(Series[7])
eth_lr = logreturns(Series[8])
doge_lr = logreturns(Series[9])


#Minmax
sp500_mm = minmax(Series[0])
nikkei_mm = minmax(Series[1])
ftse_mm = minmax(Series[2])
dax_mm = minmax(Series[3])
mex_mm = minmax(Series[4])
btc_mm = minmax(Series[5])
tether_mm = minmax(Series[6])
xrp_mm = minmax(Series[7])
eth_mm = minmax(Series[8])
doge_mm = minmax(Series[9])
