# -*- coding: utf-8 -*-
"""univariate_LSTM_importable.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IukHRHknNYAtO4iqliGOY-y1IQR0MFvH

Choose the time series and apply {\bf sequential LSTM} (https://machinelearningmastery.com/how-to-develop-lstm-models-for-time-series-forecasting/). Compare and contrast between the three techniques applied.

# Notas de la versión 4:

- Se añadieron las predicciones sobre las c.l. de las parejas cointegradas Johansen
- Se hicieron "predicciones cruzadas" de precios reescalados, tomando el modelo univariado entrando por un elemento de la pareja, digamos "A" y se usó para predecir los datos de prueba de "B" y viceversa, sa graficó la MSE y la RMSE de este enfoque vs PCC y vs DCC

- Se entrenaron 12 modelos bivariados usando las parejas cointegradas.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import typing as tp
from numpy import array
from keras.models import Sequential
from keras.layers import Input
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Dropout
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import MinMaxScaler
from keras.callbacks import EarlyStopping
import random
import os
import tensorflow as tf

import tesis_funciones_v5 as td

"""En la siguiente celda se define el modelo. La función de activación será relu, dada por:
$$relu(x) = máx\{0,x\}$$
es decir:
relu(x) = \begin{cases}
      0 & \text{si } x < 0, \\
      x & \text{si } x \geq 0.
   \end{cases}
La función de pérdida es mean squared error, dada por:
 $$
MSE = \frac{1}{n}\sum_{i=0}^{n}(y_i - \hat{y_i})^2
 $$
 Donde $y_i$ es el valor objetivo y $\hat{y_i}$ es el valor predicho por el modelo
"""

SEED = 42

# Semillas globales
os.environ['PYTHONHASHSEED'] = str(SEED)
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

n_steps = 5
n_features = 1
def create_model(n_steps:int = 5, n_features:int = 1, n_outputs:int = 1,  activation:str = "relu", seed:int = 42):
  os.environ['PYTHONHASHSEED'] = str(seed)
  random.seed(seed)
  np.random.seed(seed)
  tf.random.set_seed(seed)

  model = Sequential()
  #el modelo secuencial es util para una pila de capas simples, donde cada una tiene
  #solo un tensor de entrada y uno de salida

  #Input layer
  model.add(Input(shape=(n_steps, n_features)))
  #Hidden layer 1
  model.add(LSTM(64, activation=activation, return_sequences=True))
  #model.add(LSTM(64, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
  #Hidden layer 2
  #model.add(Dropout(0.2))
  #Hidden layer 3
  model.add(LSTM(64, activation=activation))
  #Hidden layer 4
  model.add(Dropout(0.1))
  #Hidden layer 5
  model.add(Dense(32,activation=activation))
  #model.add(Dense(4,activation='relu'))
  #model.add(Dense(4,activation='relu'))
  #Output layer
  model.add(Dense(n_outputs))
  model.compile(optimizer='adam', loss='mse')
  return model

##############################################################################
# USAMOS EL ESCALADOR DE LOS DATOS DE ENTRENAMIENTO PARA LOS DATOS DE PRUEBA #
##############################################################################
def get_train_test_TimeSeries(listed_TimeSeries:list[td.TimeSeries], listed_colors:list[str], pct: float = 0.9):
  """
  Toma una lista de objetos td.TimeSeries y hace todo el tratamiento (incluido el escalado)
  para obtener dos listas de objetos del mismo tipo, una con las TimeSeries de entrenamiento y otra con las de prueba.
  PARÁMETROS:
  - listed_TimeSeries: La lista con las TimeSeries a tratar
  - listed_colors: Los colores que se asignarán a cada TimeSeries, debe tener la misma longitud que listed_TimeSeries
  - pct: El porcentaje de datos que se utilizarán para entrenamiento, el resto se utilizará para prueba
  """
  len_train = int(len(listed_TimeSeries[0].data.values)*pct)
  len_test = len(listed_TimeSeries[0].data.values)-len_train
  train_time_series = []
  test_time_series = []
  train_data = np.zeros((len(listed_TimeSeries), len_train))
  test_data = np.zeros((len(listed_TimeSeries), len_test))
  for i in range(len(listed_TimeSeries)):
    train, test = td.train_test(listed_TimeSeries[i].data.values, pct)
    train, test = td.scaler(train, test)
    train_data[i] = train
    test_data[i] = test

    train_time_series.append(td.TimeSeries(pd.Series(train, index = td.ref_time_series.data.index[:len(train)]),
                                         listed_TimeSeries[i].name+" (train)", color = listed_colors[i]))

    test_time_series.append(td.TimeSeries(pd.Series(test, index = td.ref_time_series.data.index[len(train):]),
                                        listed_TimeSeries[i].name+" (test)", color = listed_colors[i]))
  return train_time_series, test_time_series

n_steps = 5
n_features = 1
def get_xy_sequences(listed_TimeSeries: list[td.TimeSeries], n_steps: int = n_steps, n_features: int = n_features, split_func = td.split_sequence):
  """
  Ejemplo de uso: si serie.values = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]) entonces
  x_sequence = np.array([[1,2,3,4,5], [2, 3, 4, 5, 6], [3, 4, 5, 6, 7], [4,5,6,7,8], [5,6,7,8,9]])
  y_sequence = np.array([6, 7, 8, 9, 10])
  Esta función toma una lista de objetos td.TimeSeries y devuelve dos listas de numpy arrays, una con las x_sequences de cada item
  y otra con las y_sequences.
  """
  x_sequences = []
  y_sequences = []

  i = 0
  x_sequences = []
  y_sequences = []
  for time_series in listed_TimeSeries:
    #SPLIT
    x_and_y = split_func(time_series.data.values.astype(np.float32), n_steps)
    x_sequences.append(x_and_y[0])
    y_sequences.append(x_and_y[1])
    x_sequences[i] = x_sequences[i].reshape((x_sequences[i].shape[0], x_sequences[i].shape[1], n_features))
    i+=1
  return x_sequences, y_sequences

def create_train_models(x_sequences: list[np.ndarray], y_sequences: list[np.ndarray],
                        seed: int, n_steps:int = 5, n_features:int = 1, n_outputs:int = 1, activation:str = "relu", **kwargs):
  """
  Crea y entrena len(x_sequences) modelos con create_model()
  Devuelve una lsita de modelos y otra con los historiales de entrenamiento.
  """
  models = []
  train_historys = []
  for i in range(len(x_sequences)):
    model_seed = seed + i  # o usar una lista predefinida de semillas si prefieres
    random.seed(model_seed)
    np.random.seed(model_seed)
    tf.random.set_seed(model_seed)
    nikkei_model = create_model(n_steps = n_steps, n_features = n_features, n_outputs = n_outputs,
                                activation = activation, seed = model_seed)
    nikkei_history = nikkei_model.fit(x_sequences[i], y_sequences[i], **kwargs)
    models.append(nikkei_model)
    train_historys.append(nikkei_history)
  return models, train_historys

def plot_the_losses(train_historys: list, nombres: list[str] = td.nombres, colores:list[str] = td.colores):

  """
  Grafica de Época vs Pérdida para cada modelo en train_historys.
  PARÁMETROS:
  - nombres: Una lista con las leyendas que se mostrarán en la gráfica.
  - colores: Una lista con los colores que se usarán en la gráfica.
  """
  max_losses = [round(max(losses.history['loss']), 2) for losses in train_historys]
  min_losses = [round(min(losses.history['loss']), 2) for losses in train_historys]

  plt.figure(figsize=(15, 6))
  for i in range(len(train_historys)):
    nikkei_loss = train_historys[i].history['loss']
    plt.plot(nikkei_loss, label = nombres[i], color = colores[i], marker = 'o', mfc = "none")
    plt.title("Épocas vs Pérdida")
    plt.xlabel("Época")
    plt.ylabel("Pérdida")
  plt.yticks(list(set(max_losses+min_losses)), rotation = 0)
  plt.xticks(np.arange(0, max([len(losses.history['loss']) for losses in train_historys])+1, 1)[::2])
  plt.legend()
  plt.grid()
  plt.show()

def get_the_train_curves(listed_models: list, listed_train_data: list[td.TimeSeries], listed_x_sequences:list[np.ndarray], colores: list[str]):
  """
  Toma una lista de objetos td.TimeSeries y hace predicciones sobre ellas con model.predict()
  Devuelve una lista de objetos td.TimeSeries con las predicciones.
  PARÁMETROS:
  - listed_models: Una lista con los modelos que se usarán para hacer las predicciones.
  - listed_train_data: Una lista con los datos de entrenamiento que se usarán para hacer las predicciones, solo toma el nombre
    y los índices de cada ítem para asignarlos a las predicciones.
  - listed_x_sequences: Una lista con las secuencias de entrenamiento que se usarán para hacer las predicciones.
  - colores: Una lista con los colores que se usarán para las predicciones.
  """
  train_predictions = []
  for i in range(len(listed_models)):
    train_predict = listed_models[i].predict(listed_x_sequences[i], verbose=0).flatten()
    train_predictions.append(td.TimeSeries(pd.Series(train_predict, index = listed_train_data[i].data.index[:-5]), listed_train_data[i].name+"_modelo", color =colores[i]))
  return train_predictions

#Caluculamos MSE para entrenemiento y prueba
def get_the_errors(listed_real_data: list[td.TimeSeries], listed_predictions: list[td.TimeSeries], **kwargs)->pd.DataFrame:
  """
  Toma dos listas de objetos td.TimeSeries y encuantra la MSE entre items.
  Devuelve un dataframe con las MSEs.
  """
  training_mse = []
  for i in range(len(listed_predictions)):
    training_mse.append(mean_squared_error(listed_real_data[i].data.iloc[:-5], listed_predictions[i].data))
  return pd.DataFrame(training_mse, **kwargs )

total_len = len(td.ref_time_series.data.values)
len_train = int(total_len*0.9)
len_test = total_len-len_train
train_ts = [td.TimeSeries(ts.minmax().iloc[:len_train], ts.name+"_train", ts.color) for ts in td.precios_time_series]
test_ts = [td.TimeSeries(ts.minmax().iloc[len_train:], ts.name+"_test", td.color_complementario(td.dict_colores[ts.color])) for ts in td.precios_time_series]

train_time_series, test_time_series = get_train_test_TimeSeries(td.precios_time_series, td.colores)

"""Function to split the univariate sequence into sequences of n_steps elements.
Toma una secuencia de datos (sequence) y la divide en subsecuencias de tamaño n_steps, devuelve un array con las subsecuencias (X) y otro con los siguientes datos de cada subsecuencia en la secuencia original (y).

Vamos a dividir los datos en 90% entrenamiento y 10% pruebas. Usar la normalizacion de entrenamiento para datos de pruebas. Esto es importante para que el modelo no ve los datos de pruebas.

(a) para hacer predicciones para par de series de tiempo cointegradas (12).
(b) para hacer predicciones para dos series cointegradas que tenemos usando los nueve series de tiempo (2).

Vamos a usar modelo LSTM multivariado: (a) para hacer predicciones para 5 series de tiempo de mercados financieros y 5 series de tiempo de criptomonedas.
"""

train_x_sequences, train_y_sequences = get_xy_sequences(train_time_series)
test_x_sequences, test_y_sequences = get_xy_sequences(test_time_series)

#MUESTRA UN EJEMPLO DE LAS SUBSECUENCIAS
#for i in range(5):
    #print(train_x_sequences[0][i], train_y_sequences[0][i])

early_stopping = EarlyStopping(monitor='loss', patience=10, min_delta=0.0001, mode='min', restore_best_weights=True)

"""# Para cada serie se crea un modelo y se entrena con sus respectivos datos de entrenamiento"""

models_64, train_historys_64 = create_train_models(train_x_sequences, train_y_sequences, SEED, activation = "tanh", epochs= 90, batch_size = 64 ,verbose=0, callbacks=[early_stopping])

train_predictions = get_the_train_curves(models_64, train_time_series, train_x_sequences, td.colores_complementarios)